cvmaker/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('home/', include('home.urls', namespace='home')),
    path('users/', include('users.urls', namespace='users')),
]

home/urls.py
from django.urls import path
from home.views import index, home, download


app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
    path('generate/', home, name='home'),
    path('download/<path:path>', download, name='download')
]

users/urls.py
from django.urls import path
from users.views import login, registration, profile


app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
]

home/models.py
from django.db import models


class Summary(models.Model):
    name = models.CharField(max_length=128, blank=False)
    path = models.CharField(max_length=256, blank=False)
    user = models.IntegerField(null = False, blank = False, default=0)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

home/forms.py
from django import forms
from home.models import Summary

class SummaryForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))
    surname = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))
    number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))
    education = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control py-4',
    }))
    experience = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control py-4',
    }))
    skills = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control py-4',
    }))
    languages = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control py-4',
    }))

    class Meta:
        model = Summary
        fields = ('name', 'surname', 'email', 'number', 'education', 'experience', 'skills', 'languages')

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from users.models import User
from django import forms


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль',
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите почту',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Подтвердите пароль',
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

home/views.py
from django.shortcuts import render
from home.forms import SummaryForm
from home.generator import convert
from home.models import Summary
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


def index(request):
    currentUserId = request.user.id

    summaries = Summary.objects.filter(user=currentUserId)

    context = {
        'title': 'CVMaker',
        'summaries': summaries,
    }
    return render(request, 'home/index.html', context)


@login_required(login_url='users:login')
def home(request):
    if request.method == 'POST':

        title = request.POST['title']
        name = request.POST['name']
        surname = request.POST['surname']
        email = request.POST['email']
        number = request.POST['number']
        education = request.POST['education']
        experience = request.POST['experience']
        skills = request.POST['skills']
        languages = request.POST['languages']

        return convert(title, name, surname, email, number, education, experience, skills, languages, request)

    else:
        form = SummaryForm()
    context = {'form': form}
    return render(request, 'home/home.html', context)


def download(request, path):
    with open(path, 'rb') as f:
        response = HttpResponse(f.read(), content_type='application/octet-stream')
        response['Content-Disposition'] = f'attachment; filename="resume.pdf"'
        return response

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from users.models import User
from users.forms import UserLoginForm, UserRegistrationForm
from django.contrib import auth
from django.urls import reverse


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:registration'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)


def profile(request):
    return render(request, 'users/profile.html')

home/templates/home/home.html
<!DOCTYPE html>
<html>
<head>
    <title>cvmaker</title>
    <style>
        .form-row {
            margin-bottom: 10px;
        }

        .form-row label {
            display: inline-block;
            width: 120px;
            text-align: right;
            margin-right: 10px;
        }

        .form-row input,
        .form-row textarea {
            display: inline-block;
            width: 300px;
        }
    </style>

</head>
<body>
    <h1>header</h1>

    <form id="myForm" action="{% url 'home:home' %}" method="post">
        {% csrf_token %}

        <div class="form-row">
            <label for="{{ form.title.id_for_label }}">Название:</label>
            {{ form.title }}
        </div>

        <div class="form-row">
            <label for="{{ form.name.id_for_label }}">Имя:</label>
            {{ form.name }}
        </div>

        <div class="form-row">
            <label for="{{ form.surname.id_for_label }}">Фамилия:</label>
            {{ form.surname }}
        </div>

        <div class="form-row">
            <label for="{{ form.email.id_for_label }}">Почта:</label>
            {{ form.email }}
        </div>

        <div class="form-row">
            <label for="{{ form.number.id_for_label }}">Телефон:</label>
            {{ form.number }}
        </div>

        <div class="form-row">
            <label for="{{ form.education.id_for_label }}">Образование:</label>
            {{ form.education }}
        </div>

        <div class="form-row">
            <label for="{{ form.experience.id_for_label }}">Опыт работы:</label>
            {{ form.experience }}
        </div>

        <div class="form-row">
            <label for="{{ form.skills.id_for_label }}">Навыки:</label>
            {{ form.skills }}
        </div>

        <div class="form-row">
            <label for="{{ form.languages.id_for_label }}">Языки:</label>
            {{ form.languages }}
        </div>

        <input type="submit" value="Сгенерировать резюме">
    </form>
</body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>Header</h1>
    <p>TEXT</p>
    <a href="{% url 'users:login' %}">Login</a> | <a href="{% url 'users:registration' %}">Registartion</a>
    <br><br>
    <a href='{% url 'home:home' %}'>Go to generate</a>
    {% csrf_token %}

    {% if user.is_authenticated %}
        {% if summaries %}
            <table>
                <thead>
                    <tr>
                        <th>NAME</th>
                        <th>PATH</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in summaries %}
                    <tr>
                        <td>{{ row.name }}</td>
                        <td><a href="{% url 'home:download' path=row.path %}">Download</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Вы пока что не создали ни одного резюме.</p>
        {% endif %}
    {% else %}
        <p>Необходимо авторизоваться, чтобы увидеть созданные резюме.</p>
    {% endif %}

</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Вход</title>
</head>
<body>
    <h1>Вход</h1>
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}

        <label for="username">Имя пользователя:</label>
        {{ form.username }}
        <label for="password">Пароль:</label>
        {{ form.password }}

        <input type="submit" value="Войти">
    </form>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Регистрация</title>
</head>
<body>
    <h1>Регистрация</h1>
    <form action="{% url 'users:registration' %}" method="post">
        {% csrf_token %}
        <div>

            <div>
                <label for="{{ form.username.id_for_label }}">Имя пользователя:</label>
                {{ form.username }}
            </div>

            <div>
                <label for="{{ form.email.id_for_label }}">Email:</label>
                {{ form.email }}
            </div>

            <div>
                <label for="{{ form.password1.id_for_label }}">Пароль:</label>
            {{ form.password1 }}
            </div>

            <div>
                <label for="{{ form.password2.id_for_label }}">Повторите пароль:</label>
                {{ form.password2 }}
            </div>

            <input type="submit" value="Зарегистрироваться">
        </div>

    </form>
</body>
</html>